***This is our first numpy programmme!!!! in JUPYTER NOTEBOOK***

In [1]:
import numpy as np

***By adding two square bracketts it conclude that it is 2 dimensional***

In [8]:
myarray=np.array([[3,4,5,76,8,9]],np.int64)

In [6]:
myarray[3]

76

In [4]:
myarray[0,5]

9

***~FOR CHECKING THE INFO ABOUT "myarray" MEANS no. of rows and columns***     
**~for type of data reference**

In [9]:
myarray.shape


(1, 6)

In [10]:
myarray.dtype

dtype('int64')

***WE CAN UPDATE THE ELEMENT FROM ARRAY***

In [11]:
myarray[0,3]=613

In [12]:
myarray

array([[  3,   4,   5, 613,   8,   9]], dtype=int64)

***now we start from begginnig***

# Array creation: '1' CONVERSION FROM OTHER PYTHON STRUCTURES(LIST ,TUPLE,DICTONARY)

In [13]:
listarray=np.array([[1,2,3],[5,6,7],[8,9,10]])

In [14]:
listarray

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [15]:
listarray.dtype

dtype('int32')

In [16]:
listarray.size

9

In [17]:
listarray.shape

(3, 3)

In [18]:
np.array({12,33,45,44})

array({33, 12, 45, 44}, dtype=object)

# '2' Intrinsic numpy array creation objects(arange,ones,zeros)

***zeros: it provides array default data type float***

In [19]:
zeros=np.zeros((2,5))

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

***arange: it gives an array of range less than 1 which given as parameter***

In [22]:
rng=np.arange(16)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

***linspace: it gives array of particular numbers with equal spacing***

In [27]:
lspace=np.linspace(1,8,5)

In [28]:
lspace

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

***empty: it gives random empty number of arrays with number of elements***

In [29]:
emp=np.empty((4,8))

In [30]:
emp

array([[9.45822491e-312, 1.05730048e-321, 0.00000000e+000,
        0.00000000e+000, 9.44288127e-312, 5.02034658e+175,
        1.51898766e-047, 2.65097693e-052],
       [3.92397153e+179, 1.69102468e-052, 3.88267389e-057,
        4.26125059e-096, 1.12855837e+277, 8.93168725e+271,
        7.33723594e+223, 1.70098498e+256],
       [5.49109388e-143, 1.06396443e+224, 3.96041428e+246,
        1.16318408e-028, 1.40007531e-076, 8.38817831e+165,
        5.53906053e+174, 5.24532545e+174],
       [2.24151504e+174, 3.36163259e-067, 5.41688133e-067,
        2.42191505e-028, 8.60246052e-067, 5.74015544e+180,
        1.94919988e-153, 3.46110670e-309]])

***empty_like: it copies any old array and provides the empty array with same formatting***

In [32]:
emplike=np.empty_like(lspace)

In [33]:
emplike

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

***identity: it provides the identity matrix of the size which is given in parameter*** 

In [34]:
ide=np.identity(34)

In [35]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [36]:
ide.shape

(34, 34)

In [37]:
arr=np.arange(99)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

***reshape: it change the shape of array or provide number of arrrays with equal set of elements***

In [42]:
arr=arr.reshape(3,33)

In [43]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

***ravel: to change in 1d shape ravel is used or it reverses the reshape back***


In [44]:
arr=arr.ravel()

In [45]:
arr.shape

(99,)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# NUMPY AXIS AND SOME METHODS OR ATTRIBUTES 
1D=AXIS0
2D=[AXIS0,AXIS1]

In [57]:
x=[[1,2,3],[4,5,6],[7,8,0]]

In [58]:
ar=np.array(x)

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

***sum(axis=o) means lowerdown sum or columns sum*** ***sum(axis=1) means sidewise sum or rows sum***

In [60]:
ar.sum(axis=0)

array([12, 15,  9])

In [61]:
ar.sum(axis=1)

array([ 6, 15, 15])

**ar.T transpose the array or matrix**

In [62]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 0]])

**ar.flat gives iterator we can iterate using for loop**

In [63]:
ar.flat

In [65]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
0


**ar.ndim gives detail about number of dimension**

In [66]:
ar.ndim

2

**ar.size gives no. of elements**

In [67]:
ar.size

9

**ar.nbytes gives detail about storage used by elements**

In [68]:
ar.nbytes

36

**argmax() or argmin() used to give indexing of elements where it is max or min**

In [75]:
one = np.array([1,2,3,4,5,7,66])
one.argmax()


6

In [76]:
one.argmin()

0

**argsort() used to sort elemenst according to the indexing asc to desc**

In [78]:
one.argsort()

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

**in 2d argmin() or argmax() gives in min or maximum index after arranging into 1d**

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [80]:
ar.argmin()

8

In [81]:
ar.argmax()

7

**if we apply argmax() or argmin() or argsort() by using axis parameter so it gives indexing accordingli by rows or columns**

In [82]:
ar.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [83]:
ar.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [85]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [86]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 0])

In [87]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [89]:
ar2=np.array([[1,2,33],[12,34,55],[10,23,43]])

***numpy module array allows us to perform matrix operation which is not possible in python list*** 

In [90]:
ar+ar2

array([[ 2,  4, 36],
       [16, 39, 61],
       [17, 31, 43]])

In [91]:
ar*ar2

array([[  1,   4,  99],
       [ 48, 170, 330],
       [ 70, 184,   0]])

**np.sqrt() provides us to square root of array elements**

In [92]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 0.        ]])

**ar.sum() sum the array elements and ar.max or ar.min provides maximum or minimum value**

In [93]:
ar.sum()

36

In [95]:

ar.min()

0

**FOR FINDING THE ELEMENTS IN ARRAY**

In [96]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [97]:
np.where(ar>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [98]:
type(np.where(ar>5))

tuple

***count_nonzero()it counts the non zero elements in array***

In [99]:
np.count_nonzero(ar)

8

In [100]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [101]:
ar[1,2]=0

In [102]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 0]])

***np.nonzero() it gives indexing in the form of tuple of each axis**

In [103]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [104]:
import sys
py_ar=[0,4,5,65]
np_ar=np.array(py_ar)

In [105]:
sys.getsizeof(1)* len(py_ar)

112

In [106]:
np_ar.itemsize * np_ar.size

16